apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: att7-may12-1-model-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: att7-may12-1-model-server
    app.kubernetes.io/part-of: att7-may12-1
  name: att7-may12-1-model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: att7-may12-1-model-server
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: att7-may12-1-model-server
    spec:
      initContainers:
        - name: model-file
          image: quay.io/redhat-ai-dev/whisper-small:latest
          command: ['/usr/bin/install', '/model/model.file', '/shared/']
          volumeMounts:
            - name: model-file
              mountPath: /shared
      containers:
        - env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8001"
            - name: MODEL_PATH
              value: /model/model.file
            - name: CHAT_FORMAT
              value: openchat
          image: quay.io/maysunfaisal/whispercpp:v1.7.5_7
          volumeMounts:
            - name: model-file
              mountPath: /model
          name: app-model-service
          ports:
            - containerPort: 8001
          securityContext:
            runAsNonRoot: true
      volumes:
        - name: model-file
          emptyDir: {}
