apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: att7-may12-1
  janus-idp.io/tekton: att7-may12-1
  backstage.io/kubernetes-id: att7-may12-1
  backstage.io/kubernetes-namespace: att7-may12-1
  app.kubernetes.io/part-of: att7-may12-1
resources:
  - initialize-namespace/
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
