apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: att7-may12-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: att7-may12-1
  name: att7-may12-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
